Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [12]:
N = int(input('Введите количество элементов '))
np.arange(N-1,-1,-1)

Введите количество элементов 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [31]:
N = int(input('Введите число '))
diag_mat = np.diag(np.arange(N,-1,-1),k=0)
print(diag_mat)
i = 0
sum_diag = 0
for line_mat in diag_mat:
    sum_diag += line_mat[i]
    i += 1
print(sum_diag)    

Введите число 5
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
15


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [32]:
from numpy import linalg

In [42]:
arguments = np.array([
    [4,2,1],
    [1,3,0],
    [0,5,4]
])
results = np.array([4,12,-3])
linalg.solve(arguments,results)

array([ 0.46666667,  3.84444444, -5.55555556])

In [44]:
4*0.46666667 + 2*3.84444444 -5.55555556

4.0